import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
live_config_reload= true

[shell]
program = "/bin/zsh"
args = [
    "-l", 
    # "-c", 
    # "zellij attach --index 0 || zellij"
    # "zellij attach || zellij"
]


[window] 
dimensions = { columns = 160, lines = 50 }
padding = { x = 2, y = 2 }
dynamic_padding = true 
decorations =  "full"
opacity = 1.0
option_as_alt = "Both"

[font]
# normal = { family = "Hack Nerd Font Mono", style = "Regular" }
# bold = { family = "Hack Nerd Font Mono", style = "Bold" }
# italic = { family = "Hack Nerd Font Mono", style = "Italic" }

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 16

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Beam", blinking = "Always"}
unfocused_hollow = true
blink_interval = 500
thickness = 0.15
# vi_mode_style = { shape = "Block",  blinking = "Always"}

[selection]
semantic_escape_chars =  ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[bell]
animation = "EaseOutExpo"
duration = 0

[scrolling]
history = 10000
multiplier = 3

[mouse]
hide_when_typing = true
bindings = [ 
    { mouse =  "Middle" , action =  "PasteSelection" } 
]

